name: Run ESLint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.2.0
    - name: Install modules
      run: npm i
    - name: Run ESLint
      run: npx eslint . 